name: Github Actions CI
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: resume.tex
        latexmk_use_xelatex: true
    - name: Check pdf file
      run: |
        file resume.pdf | grep -q ' PDF '
    - name: Upload resume.pdf
      run: |
        # configure git
        git config --global user.name "adityamwagh"
        git config --global user.email "adityamwagh@gmail.com"

        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git clone --depth=1 git@github.com:adityamwagh/resume.git "$GITHUB_WORKSPACE/resume"
        cp -f resume.pdf "$GITHUB_WORKSPACE/resume/resume.pdf"
        cd "$GITHUB_WORKSPACE/resume"
        git add resume.pdf
        git commit -m "[github actions] update cv"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
